### ISSUE TITLE
Renders properly on localhost, but doesn't on Github Pages

### ISSUE THREAD

**Issue by rsnk96** [jarrekk/Jalpc#68]
All the webpages render fine on `localhost`. However, when pushed to github, only the homepage renders as it should, the blog doesn't (It appears like a text only website).

The home page is [https://rsnk96.github.io/](https://rsnk96.github.io/)
and the blog is at [https://rsnk96.github.io/blog/](https://rsnk96.github.io/blog/)

**Comment by felansu** [comment]
@rsnk96, try comment `baseurl` param in _config.yml file, my config:
```
# baseurl: /
url: https://felansu.github.io
```

**Comment by rsnk96** [comment]
I commented it as you recommended, but there's still no change. Any other ideas? I'm also running an older version of the Jalpc theme

**Comment by felansu** [comment]
@rsnk96, can you update ?

**Comment by rsnk96** [comment]
Still no change. Any other ideas?

**Comment by felansu** [comment]
@rsnk96 merge with jalpc project master branch

**Comment by jarrekk** [comment]
@rsnk96 you can upgrade Jalpc as <https://github.com/jarrekk/Jalpc#upgrading-jalpc> and try again

**Comment by rsnk96** [comment]
Hey guys. Thanks. That worked like a charm! :)

However, now the header images (`header_one.jpg` and `header_two.jpg`) are not loading. I checked the main repo's rendering at [https://jarrekk.github.io/Jalpc/](https://jarrekk.github.io/Jalpc/) and it doesn't show the header images there either. Is there a fix for that, or is it possible to remove the header images?

**Comment by felansu** [comment]
@rsnk96 i'm forking your **big** repository ( >200 mg !)

**Comment by rsnk96** [comment]
Haha @felansu sorry about that. Contains >300 images.

**Comment by jarrekk** [comment]
@rsnk96 Maybe some errors occurred when I compress css & js files, you can compress it again with command `npm run build` and push all files, I will fix this issue in this repo.

**Comment by rsnk96** [comment]
@jarrekk I tried running `npm run build`. It throws the following error

```bash
$ npm run build

> Jalpc@1.1.1 build /home/rsnk96/Documents/Personal/git blog/rsnk96.github.io
> node build/purify-css.js && node build/build.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'purify-css'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rsnk96/Documents/Personal/git blog/rsnk96.github.io/build/purify-css.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Jalpc@1.1.1 build: `node build/purify-css.js && node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Jalpc@1.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rsnk96/.npm/_logs/2017-07-27T12_34_55_006Z-debug.log

```

When I display the contents of the log file mentioned in the end, the following is displayed

```bash
$ cat /home/rsnk96/.npm/_logs/2017-07-27T12_34_55_006Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Jalpc@1.1.1~prebuild: Jalpc@1.1.1
6 info lifecycle Jalpc@1.1.1~build: Jalpc@1.1.1
7 verbose lifecycle Jalpc@1.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle Jalpc@1.1.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/rsnk96/Documents/Personal/git blog/rsnk96.github.io/node_modules/.bin:/usr/local/cuda-8.0/bin:/home/rsnk96/bin:/home/rsnk96/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle Jalpc@1.1.1~build: CWD: /home/rsnk96/Documents/Personal/git blog/rsnk96.github.io
10 silly lifecycle Jalpc@1.1.1~build: Args: [ '-c', 'node build/purify-css.js && node build/build.js' ]
11 silly lifecycle Jalpc@1.1.1~build: Returned: code: 1  signal: null
12 info lifecycle Jalpc@1.1.1~build: Failed to exec build script
13 verbose stack Error: Jalpc@1.1.1 build: `node build/purify-css.js && node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid Jalpc@1.1.1
15 verbose cwd /home/rsnk96/Documents/Personal/git blog/rsnk96.github.io
16 verbose Linux 4.10.0-27-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error Jalpc@1.1.1 build: `node build/purify-css.js && node build/build.js`
22 error Exit status 1
23 error Failed at the Jalpc@1.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by felansu** [comment]
Run `npm install` for install purify-css module

**Comment by rsnk96** [comment]
After running `npm install`, `npm run build` ran successfully. However, the image still doesn't load, even when running it on `localhost`. Eagerly waiting for issue to be fixed :D, the website design is and has been awesome and I hope to continue using it.

**Comment by jarrekk** [comment]
@rsnk96 You can try to run command again and set up jekyll server at you laptop first, if there is no error then push to GitHub.

**Comment by rsnk96** [comment]
@jarrekk  It worked! Thanks a ton :). Closing the issue now
